=== samply/lens/packages/lib/src/types/options.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Lens Options",
    "description": "The options for the lens",
    "type": "object",
    "properties": {
        "iconOptions": {
            "type": "object",
            "properties": {
                "infoUrl": {
                    "type": "string",
                    "pattern": "^.+$",
                    "description": "The icon to use for the info button"
                },
                "deleteUrl": {
                    "type": "string",
                    "pattern": "^.+$",
                    "description": "The icon to use for the info button"
                },
                "selectAll": {
                    "type": "object",
                    "properties": {
                        "text": {
                            "type": "string",
                            "pattern": "^.+$",
                            "description": "The text to display for the select all button"
                        }
                    },
                    "additionalProperties": false,
                    "unevaluatedProperties": false,
                    "required": []
                }
            },
            "additionalProperties": false,
            "unevaluatedProperties": false,
            "required": []
        },
        "siteMappings":{
            "type": "object",
            "patternProperties": {
                "^.+$": {
                    "type": "string",
                    "pattern": "^.+$"
                }
            },
            "additionalProperties": false,
            "unevaluatedProperties": false,
            "required": []
        },
        "catalogueKeyToResponseKeyMap": {
            "type": "array",
            "items": {
                "type": "array",
                "items": {
                    "type": "string",
                    "pattern": "^.+$",
                    "description": "The mapping of the catalogue key to the response key"
                }
            }
        },
        "chartOptions": {
            "type": "object",
            "patternProperties": {
                "^.+$": {
                    "type": "object",
                    "properties": {
                        "legendMapping": {
                            "type": "object",
                            "patternProperties": {
                                "^.+$": {
                                    "type": "string",
                                    "pattern": "^.+$"
                                }
                            },
                            "additionalProperties": false,
                            "unevaluatedProperties": false,
                            "required": []
                        },
                        "hintText": {
                            "type": "array",
                            "items": {
                                "type": "string",
                                "pattern": "^.+$",
                                "description": "The hint text to display as overlay of the info button"
                            }
                        },
                        "aggregations": {
                            "type": "array",
                            "description": "add strings of other data keys to include in the chart",
                            "items": {
                                "type": "string",
                                "pattern": "^.+$"
                            }
                        },
                        "accumulatedValues": {
                            "type": "array",
                            "description": "aggregate values of other data keys to include in the chart",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "name": {
                                        "type": "string",
                                        "pattern": "^.+$",
                                        "description": "The name to be displayed in the chart"
                                    },
                                    "values": {
                                        "type": "array",
                                        "items": {
                                            "type": "string",
                                            "pattern": "^.+$",
                                            "description": "The data key to be aggregated"
                                        }
                                    }
                                },
                                "additionalProperties": false,
                                "unevaluatedProperties": false,
                                "required": []
                            }
                        },
                        "tooltips": {
                            "type": "object",
                            "patternProperties": {
                                "^.+$": {
                                    "type": "string",
                                    "pattern": "^.+$",
                                    "description": "The tooltip to display while hovering over the chart data"
                                }
                            },
                            "additionalProperties": false,
                            "unevaluatedProperties": false,
                            "required": []
                        }
                    },
                    "additionalProperties": false,
                    "unevaluatedProperties": false,
                    "required": []
                }
            },
            "additionalProperties": false,
            "unevaluatedProperties": false,
            "required": []
        },
        "tableOptions": {
            "type": "object",
            "properties": {
                "headerData": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "title": {
                                "type": "string",
                                "description": "the title of the column",
                                "pattern": "^.+$"
                            },
                            "dataKey": {
                                "type": "string",
                                "description": "a single key to display in the table",
                                "pattern": "^.+$"
                            },
                            "aggregatedDataKeys": {
                                "type": "array",
                                "description": "an array of keys to aggregate and display in the table as single value",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "groupCode": {
                                            "type": "string",
                                            "pattern": "^.+$"
                                        },
                                        "stratifierCode": {
                                            "type": "string",
                                            "pattern": "^.+$"
                                        },
                                        "stratumCode": {
                                            "type": "string",
                                            "pattern": "^.+$"
                                        }
                                    },
                                    "additionalProperties": false,
                                    "unevaluatedProperties": false,
                                    "required": []
                                }
                            }
                        },
                        "additionalProperties": false,
                        "unevaluatedProperties": false,
                        "required": [
                            "title"
                        ]
                    }
                },
                "claimedText": {
                    "type": "string",
                    "pattern": "^.+$",
                    "description": "The text to be displayed when query is being executed"
                }
            },
            "additionalProperties": false,
            "unevaluatedProperties": false,
            "required": ["headerData"]
        },
        "resultSummaryOptions": {
            "type": "object",
            "properties": {
                "title": {
                    "type": "string",
                    "pattern": "^.+$"
                },
                "infoButtonText": {
                    "type": "string",
                    "pattern": "^.+$"
                },
                "dataTypes": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "title": {
                                "type": "string",
                                "pattern": "^.+$"
                            },
                            "dataKey": {
                                "type": "string",
                                "pattern": "^.+$"
                            },
                            "aggregatedDataKeys": {
                                "type": "array",
                                "description": "an array of keys to aggregate and display in the result summary as single value",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "groupCode": {
                                            "type": "string",
                                            "pattern": "^.+$"
                                        },
                                        "stratifierCode": {
                                            "type": "string",
                                            "pattern": "^.+$"
                                        },
                                        "stratumCode": {
                                            "type": "string",
                                            "pattern": "^.+$"
                                        }
                                    },
                                    "additionalProperties": false,
                                    "unevaluatedProperties": false,
                                    "required": []
                                }
                            }
                        },
                        "additionalProperties": false,
                        "unevaluatedProperties": false,
                        "required": []
                    }
                }
            },
            "additionalProperties": false,
            "unevaluatedProperties": false,
            "required": []
        },
        "backends": {
            "type": "object",
            "properties": {
                "customBackends": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "pattern": "^.+$",
                        "description": "The URL of the custom backend"
                    }
                },
                "spots": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "name": {
                                "type": "string",
                                "pattern": "^.+$",
                                "description": "The name of the spot"
                            },
                            "backendMeasures": {
                                "type": "string",
                                "pattern": "^.+$",
                                "description": "The measures of the spot"
                            },
                            "url": {
                                "type": "string",
                                "pattern": "^.+$",
                                "description": "The URL of the spot"
                            },
                            "sites": {
                                "type": "array",
                                "items": {
                                    "type": "string",
                                    "pattern": "^.+$",
                                    "description": "The sites of the spot"
                                }
                            }
                        },
                        "additionalProperties": false,
                        "unevaluatedProperties": false,
                        "required": ["name", "backendMeasures", "url", "sites"]
                    }
                },
                "blazes": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "name": {
                                "type": "string",
                                "pattern": "^.+$",
                                "description": "The name of the blaze"
                            },
                            "backendMeasures": {
                                "type": "string",
                                "pattern": "^.+$",
                                "description": "The measures of the blaze"
                            },
                            "url": {
                                "type": "string",
                                "pattern": "^.+$",
                                "description": "The URL of the blaze"
                            }
                        },
                        "additionalProperties": false,
                        "unevaluatedProperties": false,
                        "required": ["name", "backendMeasures", "url"]
                    }
                }
            },
            "additionalProperties": false,
            "unevaluatedProperties": false,
            "required": []
        },
        "negotiateOptions": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string",
                    "pattern": "^.+$",
                    "description": "The measures of the blaze"
                },
                "siteMappings": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "site": {
                                "type": "string",
                                "pattern": "^.+$"
                            },
                            "collection": {
                                "type": "string",
                                "pattern": "^.+$"
                            }
                        },
                        "additionalProperties": false,
                        "unevaluatedProperties": false,
                        "required": ["site", "collection"]                    
                    }
                }
            },
            "additionalProperties": false,
            "unevaluatedProperties": false,
            "required": ["url", "siteMappings"]
            
        },
        "projectmanagerOptions": {
            "type": "object",
            "properties": {
                "newProjectUrl": {
                    "type": "string",
                    "pattern": "^.+$",
                    "description": "The measures of the blaze"
                },
                "editProjectUrl": {
                    "type": "string",
                    "pattern": "^.+$",
                    "description": "The measures of the blaze"
                },
                "siteMapping": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "site": {
                                "type": "string",
                                "pattern": "^.+$"
                            },
                            "collection": {
                                "type": "string",
                                "pattern": "^.+$"
                            }
                        },
                        "additionalProperties": false,
                        "unevaluatedProperties": false,
                        "required": ["site", "collection"]                    
                    }
                }
            },
            "additionalProperties": false,
            "unevaluatedProperties": false,
            "required": ["newProjectUrl", "editProjectUrl", "siteMapping"]
        }
    },
    "additionalProperties": false,
    "unevaluatedProperties": false,
    "required": []
}

=== samply/lens/packages/demo/public/options-cce-demo.json
{
    "iconOptions": {
        "deleteUrl": "delete_icon.svg",
        "infoUrl": "info-circle-svgrepo-com.svg",
        "selectAll": {
            "text": "Alle Hinzufügen"
        }
    },
    "siteMappings": {
        "cce-dkfz": "German Cancer Research Center",
        "cce-gr": "Gustave Roussy",
        "cce-ki": "Karolinska Institutet",
        "cce-vhio": "Vall d’Hebron Instituto de Oncología"
    },
    "catalogueKeyToResponseKeyMap": [
        [
            "gender",
            "Gender"
        ],
        [
            "age_at_diagnosis",
            "Age"
        ],
        [
            "diagnosis",
            "diagnosis"
        ],
        [
            "medicationStatements",
            "MedicationType"
        ],
        [
            "sample_kind",
            "sample_kind"
        ],
        [
            "therapy_of_tumor",
            "ProcedureType"
        ],
        [
            "75186-7",
            "75186-7"
        ]
    ],
    "chartOptions": {
        "patients": {
            "legendMapping": {
                "cce-dkfz": "German Cancer Research Center",
                "cce-gr": "Gustave Roussy",
                "cce-ki": "Karolinska Institutet",
                "cce-vhio": "Vall d’Hebron Instituto de Oncología"
            }
        },
        "gender": {
            "legendMapping": {
                "male": "male",
                "female": "female",
                "unknown": "unknown",
                "other": "other"
            }
        },
        "diagnosis": {
            "hintText": [
                "For patients with several oncological diagnoses, entries are also displayed that may not match the selected search criteria."
            ]
        },
        "age_at_diagnosis": {
            "hintText": [
                "For patients with several initial diagnoses, entries are also displayed that may lie outside the search criteria. "
            ]
        },
        "75186-7": {
            "hintText": [
                "\"deceased\": a date of death is documented or the current age is greater than 123 years.",
                "\"alive\": is assumed if no date of death is documented or the current age has not exceeded 123 years.",
                "\"unknown\": no date of birth or date of death known."
            ]
        },
        "therapy_of_tumor": {
            "hintText": [
                "For patients with several oncological diagnoses, entries are also displayed that may not match the selected search criteria."
            ],
            "aggregations": [
                "medicationStatements"
            ],
            "tooltips": {
                "OP": "Operations",
                "ST": "Radiotherapies",
                "medicationStatements": "Systemic therapies"
            }
        },
        "medicationStatements": {
            "hintText": [
                "Type of systemic therapy"
            ],
            "tooltips": {
                "CH": "Chemotherapy",
                "HO": "Hormonetherapy",
                "IM": "Immune/antibody therapy",
                "KM": "Bone marrow transplantation",
                "ZS": "Targeted substances",
                "SZ": "Stem cell transplantation (including bone marrow transplantation)",
                "AS": "Active Surveillance",
                "WS": "Wait and see",
                "WW": "Watchful Waiting",
                "SO": "Other"
            }
        },
        "sample_kind": {
            "hintText": [
                "Distribution of sample types associated with the identified patients."
            ],
            "accumulatedValues": [
                {
                    "name": "ffpe-tissue",
                    "values": [
                        "tissue-ffpe",
                        "tumor-tissue-ffpe",
                        "normal-tissue-ffpe",
                        "other-tissue-ffpe"
                    ]
                },
                {
                    "name": "frozen-tissue",
                    "values": [
                        "tissue-frozen",
                        "tumor-tissue-frozen",
                        "normal-tissue-frozen",
                        "other-tissue-frozen"
                    ]
                }
            ],
            "tooltips": {
                "ffpe-tissue": "FFPE tissue",
                "frozen-tissue": "Frozen tissue",
                "tissue-other": "Tissue other",
                "whole-blood": "Whole blood",
                "blood-serum": "Blood serum",
                "blood-plasma": "Blood plasma",
                "buffy-coat": "Buffy coat",
                "peripheral-blood-cells": "Peripheral blood cells",
                "dried-whole-blood": "Dried whole blood",
                "swab": "Swab",
                "ascites": "Ascites",
                "stool-faeces": "Stool faeces",
                "urine": "Urine",
                "csf-liquor": "Liquor",
                "bone-marrow": "Bone marrow",
                "saliva": "Saliva",
                "liquid-other": "Liquid other",
                "dna": "DNA",
                "rna": "RNA",
                "derivative-other": "Derivative other"
            },
            "legendMapping":{
                "ffpe-tissue": "FFPE tissue",
                "frozen-tissue": "Frozen tissue",
                "tissue-other": "Tissue other",
                "whole-blood": "Whole blood",
                "blood-serum": "Blood serum",
                "blood-plasma": "Blood plasma",
                "buffy-coat": "Buffy coat",
                "peripheral-blood-cells": "Peripheral blood cells",
                "dried-whole-blood": "Dried whole blood",
                "swab": "Swab",
                "ascites": "Ascites",
                "stool-faeces": "Stool faeces",
                "urine": "Urine",
                "csf-liquor": "Liquor",
                "bone-marrow": "Bone marrow",
                "saliva": "Saliva",
                "liquid-other": "Liquid other",
                "dna": "DNA",
                "rna": "RNA",
                "derivative-other": "Derivative other"
            }
        }
    },
    "tableOptions": {
        "headerData": [
            {
                "title": "Sites",
                "dataKey": "site"
            },
            {
                "title": "Patients",
                "dataKey": "patients"
            },
            {
                "title": "Specimen*",
                "aggregatedDataKeys": [
                    {
                        "groupCode": "specimen"
                    },
                    {
                        "stratifierCode": "Histologies",
                        "stratumCode": "1"
                    }
                ]
            }
        ],
        "claimedText": "Processing..."
    },
    "resultSummaryOptions": {
        "title": "Results",
        "infoButtonText": "To make re-identification more difficult, location results are modified and rounded to tens. If a location does not report a hit, zero is displayed for this location.",
        "dataTypes": [
            {
                "title": "Sites",
                "dataKey": "collections"
            },
            {
                "title": "Patients",
                "dataKey": "patients"
            },
            {
                "title": "Specimen",
                "aggregatedDataKeys": [
                    {
                        "groupCode": "specimen"
                    },
                    {
                        "stratifierCode": "Histologies",
                        "stratumCode": "1"
                    }
                ]
            }
        ]
    },
    "backends": {
        "spots": [
            {
                "name": "CCE-VDC",
                "backendMeasures": "DKTK_STRAT_DEF_IN_INITIAL_POPULATION",
                "url": "http://localhost:8055",
                "sites": [
                    "cce-dkfz",
                    "cce-gr",
                    "cce-ki",
                    "cce-vhio"
                ]
            }
        ]
    }
}
